---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: kbn
  gather_facts: false
  tasks:
  - name: Get stats of the FS object
    wait_for:
      path: /var/log/kibana/kibana.log
      state: present
      timeout: 60
  - name: Check if port 5601 is listening
    wait_for:
      port: 5601
      timeout: 60
      msg: "Timeout waiting for 5601 to respond"
